### ISSUE TITLE
Violations shown despite the file filter

### ISSUE THREAD

**Issue by musketyr** [melix/codenarc-idea#19]
Hi,

it looks to me that the file filters (at least for some check) are not respected by the IntelliJ check.

For example, the following picture shows a snippet from a specification complaining about duplicate literal but on the left side you can see that the check is disabled for files ending `Spec`

<img width="1439" alt="Snímek obrazovky 2020-05-05 v 6 27 59" src="https://user-images.githubusercontent.com/660405/81035071-9dfd8700-8e99-11ea-94a3-b4fcdfe14976.png">

**Comment by demus-nine** [comment]
Have you tried the the same filter in plain codenarc? The filter values are passed directly to the codenarc rule, so there shoudn't be any difference.
There aren't any errant spaces in the filter expression?

**Comment by musketyr** [comment]
Sadly I can't verify it now because for some reason `CodeNarc` Inspections are no longer displayed in the `Inspections` list.

Neither the inspections works.

**Comment by musketyr** [comment]
I'm using `IntelliJ IDEA 2020.2.2 Ultimate`

**Comment by demus-nine** [comment]
In IJ, you are supposed to use scopes to include/exclude/set the severity of inspections. I am probably going to include the native codenarc exclusions, when enabling importing/linking the codenarc ruleset groovy file in IJ.
