### ISSUE TITLE
Not working with IntelliJ 2020.2

### ISSUE THREAD

**Issue by occurred** [melix/codenarc-idea#20]
Starting with IntelliJ 2020.2 this Plugin is not working anymore.
It is enabled in IntelliJ, but is not shown under:
Preferences > Editor > Inspections

**Comment by demus-nine** [comment]
The many menuitems  were moved into one Codenarc item. I can find it in Inspections.

**Comment by occurred** [comment]
Thanks a lot for your time and effort, but this is not working for me, see the screenshot.
<img width="735" alt="IntelliJ-Inspections" src="https://user-images.githubusercontent.com/691252/95435204-96637200-0952-11eb-89d6-df6a8bb34f1c.png">

Please see also my Plugins:
<img width="843" alt="IntelliJ-Plugins" src="https://user-images.githubusercontent.com/691252/95435394-cf9be200-0952-11eb-9ca1-951169b9f670.png">

**Comment by demus-nine** [comment]
Which OS are you all using?

**Comment by occurred** [comment]
MacOS, before Catalina and now Big Sur, but in both cases it is not working.
In IntelliJ 2020.1.x it is still working, but from 2020.2.x on not anymore - it is just gone.

**Comment by demus-nine** [comment]
Could you look in the IDE logs to see if the plugin is mentioned? Help->Show log in files

**Comment by occurred** [comment]
Found this:
2020-11-20 07:56:15,179 [ 395501]   INFO - lij.ide.plugins.DynamicPlugins - Plugin CodeNarc is not unload-safe because it declares components
