### ISSUE TITLE
Not working in newer IntelliJ

### ISSUE THREAD

**Issue by mlasevich** [melix/codenarc-idea#21]
Same issue as (inexplicably closed) #20 Plugin does not appear to work with current versions of IntelliJ

The plugin is installed, but CodeNarc does not appear anywhere in IntelliJ except for Plu gins page. And yes, searched everywhere including `inspections`

**Comment by leoroberto** [comment]
The same with me. I installed this plugin in Intellij Idea ultimate 2020.2.3 but its doesn't appear for me, same issue #20.

**Comment by demus-nine** [comment]
Is there a blinking exclamation mark in the bottom right corner of IJ? If so, is there any more output relating to the codenarc plugin in the popup that opens when clivking it?

**Comment by leoroberto** [comment]
In my case, there isn't blinking exclamation in the botton right corner of Intellij.

**Comment by leoroberto** [comment]
> Is there a blinking exclamation mark in the bottom right corner of IJ? If so, is there any more output relating to the codenarc plugin in the popup that opens when clicking it?

In my case, there isn't blinking exclamation in the botton right corner of Intellij.

**Comment by demus-nine** [comment]
I can't reproduce this on 2020.2 or EAP. Could you upload an lDE log that includes mention of the plugin?

**Comment by musketyr** [comment]
I have the same issue for a very long time. There is no warning for CodeNarc nowhere (in terms of IDE exceptions). it simply does not pop up in the _Inspections_ anymore as displayed in #20. I'm currently running `2020.2.4` but the issue has been present in previous versions as well. The last time I can guarantee it works was on April 24, 2020, when I created an internal document on how to set it up. Could this be actually related to saved settings? See the settings file attached.


[settings.xml.zip](https://github.com/melix/codenarc-idea/files/5627041/settings.xml.zip)

**Comment by demus-nine** [comment]
Which OS are you running IJ on?

**Comment by musketyr** [comment]
macOS Catalina 10.15.7 i7 (no ARM)

**Comment by leoroberto** [comment]
![image](https://user-images.githubusercontent.com/27290347/101770880-e9c77d00-3ac7-11eb-96a8-649ec875a80c.png)

**Comment by kfuto** [comment]
Has anyone been able to get this plugin to appear under inspections on newer versions of IntelliJ yet?  This plugin previously worked for me on 2019 versions of IntelliJ.   I do not see any mention of the plugin in the IDE logs.  Other plugins for inspections are working correctly. 

IntelliJ IDEA 2020.3.1 (Community Edition)
Windows 10

**Comment by musketyr** [comment]
it looks like the components are no longer scanned for being tool providers and you need to explicitly declare the the `inspectionToolProvider` extension - see #22

**Comment by ratnahalder** [comment]
I'm having similar issue in the new IntelliJ, can't understand why this issue is closed. And if I need to explicitly declare the inspectionToolProvider, then what should be config info?

**Comment by musketyr** [comment]
@ratnahalder can you elaborate a bit? What version of IntelliJ and CodeNarc plugin are you using? How does your CodeNarc inspections settings look like?

<img width="993" alt="Snímek obrazovky 2023-05-23 v 17 08 35" src="https://github.com/melix/codenarc-idea/assets/660405/607d7617-7493-450c-8319-3befcd6e488a">
