### ISSUE TITLE
Upgrade CodeNarc to 2.0.0

### ISSUE THREAD

**Issue by djpeinado** [melix/codenarc-idea#23]
I would like to use new CodeNarc 2.0.0 features like [Disabling rules from comments](https://github.com/CodeNarc/CodeNarc/blob/v2.0.0/docs/codenarc-configuring-rules.md#disabling-rules-from-comments).

https://github.com/CodeNarc/CodeNarc/releases/tag/v2.0.0

Thanks in advance

**Comment by musketyr** [comment]
done in master and in the beta channel
