### ISSUE TITLE
Doesn't work on Intellij Idea 2020.1

### ISSUE THREAD

**Issue by arun-kottayil-pinc** [melix/codenarc-idea#39]
First of all I don't know how to check if it is working or now. On the plugin hoe page there is no new screenshot of how it is supposed to work. It doesn't seem to do anything on intelliJ 2020.1

**Comment by musketyr** [comment]
Hi,

can you tell me what version of the plugin you have installed?

First of all, you should be able to see the CodeNarc in the inspections settings:

<img width="916" alt="Snímek obrazovky 2021-05-04 v 15 05 03" src="https://user-images.githubusercontent.com/660405/117007804-58f97400-acea-11eb-9634-53845bf9a75f.png">

Then you should see the particular issues highlighted in your Groovy code

**Comment by arun-kottayil-pinc** [comment]
Sorry. False alarm. It was not activated under the inspections section. Thank you for the screenshot. 
Honestly I did not know that there is a inspections setting. Can you add this step to the plugin home page or on the plugin information that shows up when we search for the plugin in intelliJ ?
one more question, can we override whatever default config is and use a custom config ? we are using the codenarc plugin in our gradle build and we specify a custom rules file like this one
![image](https://user-images.githubusercontent.com/79944488/117032595-9ac8f100-accf-11eb-871d-e34ede1e9107.png)

**Comment by musketyr** [comment]
This is already very old request #9. I will certainly add it into docs.

**Comment by arun-kottayil-pinc** [comment]
not a defect. Closing the issue
