### ISSUE TITLE
Do not apply to file / files matching not working

### ISSUE THREAD

**Issue by itd-dha** [melix/codenarc-idea#59]
Hi,

I have the feeling the "Do not apply to file names" and "Do not apply to files matching" input is not working in IntelliJ.
I want to exclude the "build.gradle" file in my root folder from CodeNarcs Formatting rules, but everything I try, I can not get this file ignored other then deactivating the whole rule.

Rule: Closure statement on opening line of multiple line closure

Tested:
Do not apply to file names:
- build.gradle
- build
- gradle

Do not apply to files matching:
- *.gradle
- .*.gradle
- [a-zA-Z0-9]*.gradle
- build.gradle

IntelliJ Version: 2021.2.4
CodeNarc Plugin Version: 4.4.0

Any idea what I am doing wrong?
Do I have to switch to Beta channel and get a newer version of plugin?

**Comment by musketyr** [comment]
Hi, sorry for a late reply.

Yes, you should try the beta channel to get the newest version of the plugin. Let me know if the issue still persist with the latest version.

**Comment by itd-dha** [comment]
Hi, thanks for your answer.

I switched to beta channel and updated the plugin, still the problem remains:

Example:
-> In settings I set file or matches to ignore rule "Block starts with empty line" for build.gradle
-> Intellij writes the following to my Intellij profile
```xml
<inspection_tool class="CodeNarc.BlockStartsWithBlankLine" enabled="true" level="SERVER PROBLEM" enabled_by_default="true">
    <option name="doNotApplyToFileNames" value="build.gradle" />
    <option name="doNotApplyToFilesMatching" value="[a-zA-Z0-9]*.gradle" />
</inspection_tool>
```

But still it finds this rule in my build.gradle
![grafik](https://user-images.githubusercontent.com/88084960/200387046-53641e6f-8bab-4096-9175-cb6c6150223f.png)

For matching file I tested "build" or "gradle"
For matching regex I tested "(.)*.gradle" or ".*.gradle"
Same result.

**Comment by itd-dha** [comment]
Wow, thanks for your time fixing this, I will test it out right away!
