### ISSUE TITLE
Support intelliJ 2023.1

### ISSUE THREAD

**Issue by Nierhoff** [melix/codenarc-idea#65]
Currently version 6.0.0 of codenarc plugin does not support IntelliJ 2023.1.

![image](https://user-images.githubusercontent.com/2183902/228806020-37a4bbfa-0ce0-4b61-ad65-081853eebfc9.png)

There has been created 2 PR's to try to fix this:
https://github.com/melix/codenarc-idea/pull/64
https://github.com/melix/codenarc-idea/pull/63

If the slicing of the PR's needs to be different or any other changes are suggested please reach out to me.

**Comment by musketyr** [comment]
done by #68
